apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-mq.openshift-operators: ''
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: ibm-mq
  namespace: openshift-operators
spec:
  channel: v3.0
  installPlanApproval: Automatic
  name: ibm-mq
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace