apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
    argocd.argoproj.io/sync-wave: "100"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: mq
  namespace: {{ .Values.namespace }}
  finalizers:
    - finalizer.queuemanagers.mq.ibm.com
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: NonProduction
  queueManager:
    availability:
      type: NativeHA
    name: CUSTOM
    storage:
      defaultClass: {{ .Values.storage.fileStorage }}
      queueManager:
        type: persistent-claim
  version: 9.3.4.0-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
